### ISSUE TITLE
Swtich to DAWG as a default storage and lookup engine

### ISSUE THREAD

**Issue by mrgambal** [mrgambal/elasticsearch-ukrainian-lemmatizer#1]
As long as CSV format is very inefficient we must make our way to improve this by switching to another engine.
The best alternative suggested by @dchaplinsky is Directed Acyclic Word Graph. The structure, whose name describes all you need to know from the very first sight.
I've seen great implementations in Python and C++ (like https://github.com/kmike/DAWG) but Java-versions don't have dict-like behaviour we look for (see `BytesDAWG` class in @kmike's implementation).

**Comment by mrgambal** [comment]
Gonna take a look at https://github.com/Qualtagh/DAWG/blob/master/src/main/java/org/quinto/dawg/DAWGMap.java

**Comment by arysin** [comment]
https://github.com/morfologik/morfologik-stemming/tree/master/morfologik-tools (which is used by LanguageTool) is pretty efficient, but not sure if suitable for lucene.

**Comment by anti-social** [comment]
See my repository: https://github.com/anti-social/jmorphy2
This is `pymorphy2` port to Java. Also there are Lucene, Solr and Elasticsearch plugins. Recently I added support for ukrainian language.

**Comment by mrgambal** [comment]
@anti-social that's great! Until @arysin work hits stable versions of these tools your solution will back up users.

**Comment by mrgambal** [comment]
Addressed in [release v 1.4.1](https://github.com/mrgambal/elasticsearch-ukrainian-lemmatizer/releases/tag/1.4.1).
