### ISSUE TITLE
Please update the dictionary

### ISSUE THREAD

**Issue by arysin** [mrgambal/elasticsearch-ukrainian-lemmatizer#4]
Converted from the latest dict_uk sources:
https://drive.google.com/open?id=0B4mUAylazDVbaEoxTmx6UXY4Tkk

(excluded are rare forms of colloquial verb infinitives and most vocative for inanim nouns).

**Comment by mrgambal** [comment]
Addressed in [release v 1.4.1](https://github.com/mrgambal/elasticsearch-ukrainian-lemmatizer/releases/tag/1.4.1).
